spring:
  application:
    name: springfox-swagger3
server:
  port: 8080
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://127.0.0.1:${server.port}
