spring:
  application:
    name: spring-boot-keycloak

server:
  port: 8080

keycloak:
  auth-server-url: http://127.0.0.1:8180/auth
  realm: SpringBootKeycloak
  resource: login-app
  public-client: true
#  security-constraints[0]:
#    authRoles[0]: user
#    securityCollections[0]:
#      patterns[0]: /customers/*
  principal-attribute: preferred_username