server:
  port: 9091

spring:
  application:
    name: oauth2-authorization-code-client-resttemplate-jdbc
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2_client_db?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456789
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  mvc:
    converters:
      preferred-json-mapper: jackson

oauth2:
  client:
    client-id: client-a
    client-secret: client-a-secret
    redirect_uri: http://127.0.0.1:${server.port}/callback
    response_type: code
    scope: read_user_info
  server:
    host: http://127.0.0.1:8085
    authorize-url: ${oauth2.server.host}/oauth/authorize
    token-url: ${oauth2.server.host}/oauth/token
    check-token-url: ${oauth2.server.host}/oauth/check_token